"""
This module contains functions that are not quite related to the main
logic, e.g. functions for parsing files generated by certain software.
"""

def parse_art_orientation(aln_files):
    """
    Receives path to *.aln file generated by art_illumina.
    Returns dictionary that maps ids of reads to their orientation which is
    either '+' or '-'. '-' means that the read is reverse complement of
    original sequence.
    """
    orientation = {}
    for aln_file in aln_files:
        with open(aln_file, 'r', encoding='utf-8') as f:
            for line in f.readlines():
                if line[0] != '>':
                    continue
                read_info = line[:-1].split('\t')
                read_id, read_orientation = '-'.join(read_info[1].split('-')[0:2]), read_info[-1]
                orientation[read_id] = read_orientation
    return orientation
